name: Continous Deployment

on:
  push:
    branches:
      - "cd"

jobs:
  Continous_deployment:
    name: Continous Deployment Heroku
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
        java-version: 1.13
    - run: mvn package -DskipTests
          #Builds a Docker and deploys on Heroku
    - name: Deploy on Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        usedocker: true