################### REQUIERED SECRETS################################
#
#       dockerhub username: ${{secrets.dockerhub_username}}
#       dockerhub password: ${{secrets.dockerhub_password}}
#       target ssh host: ${{ secrets.HOST }}
#       proyect name: ${{secrets.proyect_name}}
#       target host ssh private key: ${{ secrets.SSH }}

################### DEFAULT VALUES ##################################
#
#       target host username: ubuntu 
#       java-version: 1.13
#       target docker ports: -p 8080:8080
#       "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV


name: Continous Deployment Docker

on:
  push:
    branches:
      #- "main"
      - "no-branch"


jobs:
  Continous_deployment:
    name: Continous Deployment SSH
    runs-on: ubuntu-latest
    steps:

    #### CHECKOUT REPOSITORY ########################################################
      - name: Checkout Repository
        uses: actions/checkout@v1

    #### SET ENVIRONMENT VALUE ######################################################
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    #### SETUP JDK ##################################################################
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 1.13

    #### COMPILE AND PACKAGE ########################################################
      - name: Maven Package without test
        run: mvn -B clean package -DskipTests

    #### DOCKER BUILD AND PUSH ######################################################
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{secrets.dockerhub_username}}
          password: ${{secrets.dockerhub_password}}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.dockerhub_username}}/${{secrets.proyect_name}}:${{ env.RELEASE_VERSION }}


      #######################SSH  DOCKER DEPLOY##########################
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH }}
          script: sudo docker stop ${{secrets.proyect_name}} |
                  sudo docker remove ${{secrets.proyect_name}} |
                  sudo docker run -d --name=${{secrets.proyect_name}} -p 8080:8080 ${{secrets.dockerhub_username}}/${{secrets.proyect_name}}:${{ env.RELEASE_VERSION }}